# 01_5.4.2_Computing_the_Bidiagonal_SVD_to_High_Relative_Accuracy

"""
Lecture: 5_The_Symmetric_Eigenproblem_and_Singular_Value_Decomposition/5.4_Algorithms_for_the_Singular_Value_Decomposition
Content: 01_5.4.2_Computing_the_Bidiagonal_SVD_to_High_Relative_Accuracy
"""

